### ISSUE TITLE
Memory issues with Ardublock v20131031 and Arduino 1.5.5

### ISSUE THREAD

**Issue by GreggShort** [taweili/ardublock#77]
When I try and open a second sketch (.ino NOT an .abp), I'm getting a stack heap error when ardublock v20131031 is installed as a tool. (Windows 8.1)  Not sure if the problem is a memory leak with ardublock, or the allocated memory in configuration.txt needs to be increased.  Problem goes away if I rename the tools directory (holding ardublock) to "fubar-tools" 

Here's an example error.

Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
    at javax.swing.JScrollPane.createViewport(Unknown Source)
    at javax.swing.JScrollPane.<init>(Unknown Source)
    at edu.mit.blocks.codeblockutil.CTracklessScrollPane$1.<init>(CTracklessScrollPane.java:146)
    at edu.mit.blocks.codeblockutil.CTracklessScrollPane.<init>(CTracklessScrollPane.java:148)
    at edu.mit.blocks.codeblockutil.CPopupMenu.<init>(CPopupMenu.java:41)
    at edu.mit.blocks.codeblockutil.LabelWidget$LabelMenu.<init>(LabelWidget.java:511)
    at edu.mit.blocks.codeblockutil.LabelWidget$LabelMenu.<init>(LabelWidget.java:506)
    at edu.mit.blocks.codeblockutil.LabelWidget.<init>(LabelWidget.java:52)
    at edu.mit.blocks.renderable.BlockLabel$1.<init>(BlockLabel.java:81)
    at edu.mit.blocks.renderable.BlockLabel.<init>(BlockLabel.java:81)
    at edu.mit.blocks.renderable.SocketLabel.<init>(SocketLabel.java:15)
    at edu.mit.blocks.renderable.RenderableBlock.synchronizeSockets(RenderableBlock.java:544)
    at edu.mit.blocks.renderable.RenderableBlock.<init>(RenderableBlock.java:249)
    at edu.mit.blocks.renderable.RenderableBlock.<init>(RenderableBlock.java:186)
    at edu.mit.blocks.renderable.FactoryRenderableBlock.<init>(FactoryRenderableBlock.java:40)
    at edu.mit.blocks.workspace.PageDrawerLoadingUtils.loadBlockDrawerSets(PageDrawerLoadingUtils.java:236)
    at edu.mit.blocks.workspace.Workspace.loadWorkspaceFrom(Workspace.java:849)
    at edu.mit.blocks.controller.WorkspaceController.loadFreshWorkspace(WorkspaceController.java:397)
    at com.ardublock.core.Context.resetWorksapce(Context.java:110)
    at com.ardublock.core.Context.<init>(Context.java:76)
    at com.ardublock.core.Context.getContext(Context.java:63)
    at com.ardublock.ui.OpenblocksFrame.<init>(OpenblocksFrame.java:71)
    at com.ardublock.ui.ArduBlockToolFrame.<init>(ArduBlockToolFrame.java:3)
    at com.ardublock.ArduBlockTool.init(ArduBlockTool.java:28)
    at processing.app.Editor.addTools(Editor.java:824)
    at processing.app.Editor.buildToolsMenu(Editor.java:693)
    at processing.app.Editor.buildMenuBar(Editor.java:486)
    at processing.app.Editor.<init>(Editor.java:212)
    at processing.app.Base.handleOpen(Base.java:846)
    at processing.app.Base.handleOpen(Base.java:811)
    at processing.app.Base$8.actionPerformed(Base.java:1604)
    at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)

**Comment by multiplo** [comment]
You should edit the file inside of Contents/Resources/Java/lib/preferences.txt and replace the line for run.options.memory.maximum=256 with another value like 512 ( that worked in my case at least )
